// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.0
// source: exampleservice.proto

package backendservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataBackendClient is the client API for DataBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataBackendClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	GetAuthToken(ctx context.Context, in *AuthTokenRequest, opts ...grpc.CallOption) (*AuthTokenReply, error)
	GetTypesOfData(ctx context.Context, in *DataInfoRequest, opts ...grpc.CallOption) (*DataInfoReply, error)
	GetData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataReply, error)
}

type dataBackendClient struct {
	cc grpc.ClientConnInterface
}

func NewDataBackendClient(cc grpc.ClientConnInterface) DataBackendClient {
	return &dataBackendClient{cc}
}

func (c *dataBackendClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/backendservice.DataBackend/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataBackendClient) GetAuthToken(ctx context.Context, in *AuthTokenRequest, opts ...grpc.CallOption) (*AuthTokenReply, error) {
	out := new(AuthTokenReply)
	err := c.cc.Invoke(ctx, "/backendservice.DataBackend/GetAuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataBackendClient) GetTypesOfData(ctx context.Context, in *DataInfoRequest, opts ...grpc.CallOption) (*DataInfoReply, error) {
	out := new(DataInfoReply)
	err := c.cc.Invoke(ctx, "/backendservice.DataBackend/GetTypesOfData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataBackendClient) GetData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataReply, error) {
	out := new(DataReply)
	err := c.cc.Invoke(ctx, "/backendservice.DataBackend/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataBackendServer is the server API for DataBackend service.
// All implementations must embed UnimplementedDataBackendServer
// for forward compatibility
type DataBackendServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	GetAuthToken(context.Context, *AuthTokenRequest) (*AuthTokenReply, error)
	GetTypesOfData(context.Context, *DataInfoRequest) (*DataInfoReply, error)
	GetData(context.Context, *DataRequest) (*DataReply, error)
	mustEmbedUnimplementedDataBackendServer()
}

// UnimplementedDataBackendServer must be embedded to have forward compatible implementations.
type UnimplementedDataBackendServer struct {
}

func (UnimplementedDataBackendServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedDataBackendServer) GetAuthToken(context.Context, *AuthTokenRequest) (*AuthTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthToken not implemented")
}
func (UnimplementedDataBackendServer) GetTypesOfData(context.Context, *DataInfoRequest) (*DataInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTypesOfData not implemented")
}
func (UnimplementedDataBackendServer) GetData(context.Context, *DataRequest) (*DataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedDataBackendServer) mustEmbedUnimplementedDataBackendServer() {}

// UnsafeDataBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataBackendServer will
// result in compilation errors.
type UnsafeDataBackendServer interface {
	mustEmbedUnimplementedDataBackendServer()
}

func RegisterDataBackendServer(s grpc.ServiceRegistrar, srv DataBackendServer) {
	s.RegisterService(&DataBackend_ServiceDesc, srv)
}

func _DataBackend_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataBackendServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendservice.DataBackend/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataBackendServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataBackend_GetAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataBackendServer).GetAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendservice.DataBackend/GetAuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataBackendServer).GetAuthToken(ctx, req.(*AuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataBackend_GetTypesOfData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataBackendServer).GetTypesOfData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendservice.DataBackend/GetTypesOfData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataBackendServer).GetTypesOfData(ctx, req.(*DataInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataBackend_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataBackendServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendservice.DataBackend/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataBackendServer).GetData(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataBackend_ServiceDesc is the grpc.ServiceDesc for DataBackend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataBackend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backendservice.DataBackend",
	HandlerType: (*DataBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _DataBackend_SayHello_Handler,
		},
		{
			MethodName: "GetAuthToken",
			Handler:    _DataBackend_GetAuthToken_Handler,
		},
		{
			MethodName: "GetTypesOfData",
			Handler:    _DataBackend_GetTypesOfData_Handler,
		},
		{
			MethodName: "GetData",
			Handler:    _DataBackend_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exampleservice.proto",
}
