// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: exampleservice.proto

package backendservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_exampleservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exampleservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_exampleservice_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_exampleservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_exampleservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_exampleservice_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AuthTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokenRequest) Reset() {
	*x = AuthTokenRequest{}
	mi := &file_exampleservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenRequest) ProtoMessage() {}

func (x *AuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exampleservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenRequest.ProtoReflect.Descriptor instead.
func (*AuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_exampleservice_proto_rawDescGZIP(), []int{2}
}

func (x *AuthTokenRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type AuthTokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authtoken     string                 `protobuf:"bytes,1,opt,name=authtoken,proto3" json:"authtoken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokenReply) Reset() {
	*x = AuthTokenReply{}
	mi := &file_exampleservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenReply) ProtoMessage() {}

func (x *AuthTokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_exampleservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenReply.ProtoReflect.Descriptor instead.
func (*AuthTokenReply) Descriptor() ([]byte, []int) {
	return file_exampleservice_proto_rawDescGZIP(), []int{3}
}

func (x *AuthTokenReply) GetAuthtoken() string {
	if x != nil {
		return x.Authtoken
	}
	return ""
}

type DataInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Authtoken     string                 `protobuf:"bytes,2,opt,name=authtoken,proto3" json:"authtoken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataInfoRequest) Reset() {
	*x = DataInfoRequest{}
	mi := &file_exampleservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInfoRequest) ProtoMessage() {}

func (x *DataInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exampleservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInfoRequest.ProtoReflect.Descriptor instead.
func (*DataInfoRequest) Descriptor() ([]byte, []int) {
	return file_exampleservice_proto_rawDescGZIP(), []int{4}
}

func (x *DataInfoRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DataInfoRequest) GetAuthtoken() string {
	if x != nil {
		return x.Authtoken
	}
	return ""
}

type DataInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasection   string                 `protobuf:"bytes,1,opt,name=datasection,proto3" json:"datasection,omitempty"`
	Datalength    int32                  `protobuf:"varint,2,opt,name=datalength,proto3" json:"datalength,omitempty"`
	Minchunk      int32                  `protobuf:"varint,3,opt,name=minchunk,proto3" json:"minchunk,omitempty"`
	Maxchunk      int32                  `protobuf:"varint,4,opt,name=maxchunk,proto3" json:"maxchunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataInformation) Reset() {
	*x = DataInformation{}
	mi := &file_exampleservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInformation) ProtoMessage() {}

func (x *DataInformation) ProtoReflect() protoreflect.Message {
	mi := &file_exampleservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInformation.ProtoReflect.Descriptor instead.
func (*DataInformation) Descriptor() ([]byte, []int) {
	return file_exampleservice_proto_rawDescGZIP(), []int{5}
}

func (x *DataInformation) GetDatasection() string {
	if x != nil {
		return x.Datasection
	}
	return ""
}

func (x *DataInformation) GetDatalength() int32 {
	if x != nil {
		return x.Datalength
	}
	return 0
}

func (x *DataInformation) GetMinchunk() int32 {
	if x != nil {
		return x.Minchunk
	}
	return 0
}

func (x *DataInformation) GetMaxchunk() int32 {
	if x != nil {
		return x.Maxchunk
	}
	return 0
}

type DataInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          string                 `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Alldatainfo   []*DataInformation     `protobuf:"bytes,2,rep,name=alldatainfo,proto3" json:"alldatainfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataInfoReply) Reset() {
	*x = DataInfoReply{}
	mi := &file_exampleservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInfoReply) ProtoMessage() {}

func (x *DataInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_exampleservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInfoReply.ProtoReflect.Descriptor instead.
func (*DataInfoReply) Descriptor() ([]byte, []int) {
	return file_exampleservice_proto_rawDescGZIP(), []int{6}
}

func (x *DataInfoReply) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *DataInfoReply) GetAlldatainfo() []*DataInformation {
	if x != nil {
		return x.Alldatainfo
	}
	return nil
}

type DataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Authtoken      string                 `protobuf:"bytes,2,opt,name=authtoken,proto3" json:"authtoken,omitempty"`
	Datarequested  string                 `protobuf:"bytes,3,opt,name=datarequested,proto3" json:"datarequested,omitempty"`
	Datastartindex int32                  `protobuf:"varint,4,opt,name=datastartindex,proto3" json:"datastartindex,omitempty"`
	Datachunksize  int32                  `protobuf:"varint,5,opt,name=datachunksize,proto3" json:"datachunksize,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_exampleservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exampleservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_exampleservice_proto_rawDescGZIP(), []int{7}
}

func (x *DataRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DataRequest) GetAuthtoken() string {
	if x != nil {
		return x.Authtoken
	}
	return ""
}

func (x *DataRequest) GetDatarequested() string {
	if x != nil {
		return x.Datarequested
	}
	return ""
}

func (x *DataRequest) GetDatastartindex() int32 {
	if x != nil {
		return x.Datastartindex
	}
	return 0
}

func (x *DataRequest) GetDatachunksize() int32 {
	if x != nil {
		return x.Datachunksize
	}
	return 0
}

type DataItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stringval     string                 `protobuf:"bytes,1,opt,name=stringval,proto3" json:"stringval,omitempty"`
	IntVal        int32                  `protobuf:"varint,2,opt,name=intVal,proto3" json:"intVal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataItem) Reset() {
	*x = DataItem{}
	mi := &file_exampleservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataItem) ProtoMessage() {}

func (x *DataItem) ProtoReflect() protoreflect.Message {
	mi := &file_exampleservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataItem.ProtoReflect.Descriptor instead.
func (*DataItem) Descriptor() ([]byte, []int) {
	return file_exampleservice_proto_rawDescGZIP(), []int{8}
}

func (x *DataItem) GetStringval() string {
	if x != nil {
		return x.Stringval
	}
	return ""
}

func (x *DataItem) GetIntVal() int32 {
	if x != nil {
		return x.IntVal
	}
	return 0
}

type DataReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*DataItem            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataReply) Reset() {
	*x = DataReply{}
	mi := &file_exampleservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataReply) ProtoMessage() {}

func (x *DataReply) ProtoReflect() protoreflect.Message {
	mi := &file_exampleservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataReply.ProtoReflect.Descriptor instead.
func (*DataReply) Descriptor() ([]byte, []int) {
	return file_exampleservice_proto_rawDescGZIP(), []int{9}
}

func (x *DataReply) GetData() []*DataItem {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_exampleservice_proto protoreflect.FileDescriptor

const file_exampleservice_proto_rawDesc = "" +
	"\n" +
	"\x14exampleservice.proto\x12\x0ebackendservice\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\".\n" +
	"\x10AuthTokenRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\".\n" +
	"\x0eAuthTokenReply\x12\x1c\n" +
	"\tauthtoken\x18\x01 \x01(\tR\tauthtoken\"K\n" +
	"\x0fDataInfoRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\tauthtoken\x18\x02 \x01(\tR\tauthtoken\"\x8b\x01\n" +
	"\x0fDataInformation\x12 \n" +
	"\vdatasection\x18\x01 \x01(\tR\vdatasection\x12\x1e\n" +
	"\n" +
	"datalength\x18\x02 \x01(\x05R\n" +
	"datalength\x12\x1a\n" +
	"\bminchunk\x18\x03 \x01(\x05R\bminchunk\x12\x1a\n" +
	"\bmaxchunk\x18\x04 \x01(\x05R\bmaxchunk\"f\n" +
	"\rDataInfoReply\x12\x12\n" +
	"\x04info\x18\x01 \x01(\tR\x04info\x12A\n" +
	"\valldatainfo\x18\x02 \x03(\v2\x1f.backendservice.DataInformationR\valldatainfo\"\xbb\x01\n" +
	"\vDataRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\tauthtoken\x18\x02 \x01(\tR\tauthtoken\x12$\n" +
	"\rdatarequested\x18\x03 \x01(\tR\rdatarequested\x12&\n" +
	"\x0edatastartindex\x18\x04 \x01(\x05R\x0edatastartindex\x12$\n" +
	"\rdatachunksize\x18\x05 \x01(\x05R\rdatachunksize\"@\n" +
	"\bDataItem\x12\x1c\n" +
	"\tstringval\x18\x01 \x01(\tR\tstringval\x12\x16\n" +
	"\x06intVal\x18\x02 \x01(\x05R\x06intVal\"9\n" +
	"\tDataReply\x12,\n" +
	"\x04data\x18\x01 \x03(\v2\x18.backendservice.DataItemR\x04data2\xc2\x02\n" +
	"\vDataBackend\x12F\n" +
	"\bSayHello\x12\x1c.backendservice.HelloRequest\x1a\x1a.backendservice.HelloReply\"\x00\x12R\n" +
	"\fGetAuthToken\x12 .backendservice.AuthTokenRequest\x1a\x1e.backendservice.AuthTokenReply\"\x00\x12R\n" +
	"\x0eGetTypesOfData\x12\x1f.backendservice.DataInfoRequest\x1a\x1d.backendservice.DataInfoReply\"\x00\x12C\n" +
	"\aGetData\x12\x1b.backendservice.DataRequest\x1a\x19.backendservice.DataReply\"\x00BAZ.techops.technical.challenge.com/backendservice\xaa\x02\x0ebackendserviceb\x06proto3"

var (
	file_exampleservice_proto_rawDescOnce sync.Once
	file_exampleservice_proto_rawDescData []byte
)

func file_exampleservice_proto_rawDescGZIP() []byte {
	file_exampleservice_proto_rawDescOnce.Do(func() {
		file_exampleservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exampleservice_proto_rawDesc), len(file_exampleservice_proto_rawDesc)))
	})
	return file_exampleservice_proto_rawDescData
}

var file_exampleservice_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_exampleservice_proto_goTypes = []any{
	(*HelloRequest)(nil),     // 0: backendservice.HelloRequest
	(*HelloReply)(nil),       // 1: backendservice.HelloReply
	(*AuthTokenRequest)(nil), // 2: backendservice.AuthTokenRequest
	(*AuthTokenReply)(nil),   // 3: backendservice.AuthTokenReply
	(*DataInfoRequest)(nil),  // 4: backendservice.DataInfoRequest
	(*DataInformation)(nil),  // 5: backendservice.DataInformation
	(*DataInfoReply)(nil),    // 6: backendservice.DataInfoReply
	(*DataRequest)(nil),      // 7: backendservice.DataRequest
	(*DataItem)(nil),         // 8: backendservice.DataItem
	(*DataReply)(nil),        // 9: backendservice.DataReply
}
var file_exampleservice_proto_depIdxs = []int32{
	5, // 0: backendservice.DataInfoReply.alldatainfo:type_name -> backendservice.DataInformation
	8, // 1: backendservice.DataReply.data:type_name -> backendservice.DataItem
	0, // 2: backendservice.DataBackend.SayHello:input_type -> backendservice.HelloRequest
	2, // 3: backendservice.DataBackend.GetAuthToken:input_type -> backendservice.AuthTokenRequest
	4, // 4: backendservice.DataBackend.GetTypesOfData:input_type -> backendservice.DataInfoRequest
	7, // 5: backendservice.DataBackend.GetData:input_type -> backendservice.DataRequest
	1, // 6: backendservice.DataBackend.SayHello:output_type -> backendservice.HelloReply
	3, // 7: backendservice.DataBackend.GetAuthToken:output_type -> backendservice.AuthTokenReply
	6, // 8: backendservice.DataBackend.GetTypesOfData:output_type -> backendservice.DataInfoReply
	9, // 9: backendservice.DataBackend.GetData:output_type -> backendservice.DataReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_exampleservice_proto_init() }
func file_exampleservice_proto_init() {
	if File_exampleservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exampleservice_proto_rawDesc), len(file_exampleservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exampleservice_proto_goTypes,
		DependencyIndexes: file_exampleservice_proto_depIdxs,
		MessageInfos:      file_exampleservice_proto_msgTypes,
	}.Build()
	File_exampleservice_proto = out.File
	file_exampleservice_proto_goTypes = nil
	file_exampleservice_proto_depIdxs = nil
}
